[package]
name = "ls"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2"
terminal_size = "0.2.6"
xattr = "0.2.2"
users = "0.11.0"
chrono = "0.4"
acl-sys = "1.2.2"
libc = "0.2.144"
